cybertec-postgresql/pg_timetable

samples/BasicSQL.sql
samples/Chain.sql
samples/CronStyle.sql
samples/Download.sql
samples/Log.sql
samples/Mail.sql
samples/ManyTasks.sql
samples/NoOp.sql
samples/RemoteDB.sql
samples/Shell.sql
samples/Sleep.sql

Make samples executable by any client. Fix issues. Prettify code

---

sql/job-functions.sql

added LPAD for leading numbers in generated chain_name
Removed client_name in Insert for timetable.chain_execution_config

Fix for Bug #54

---

sql/job-functions.sql

Fixed "starting range value was not included in RangeWithSteps calc"

Fixed RangeWithSteps

---

internal/pgengine/access.go
internal/pgengine/bootstrap.go
internal/pgengine/pgengine_test.go
internal/pgengine/transaction.go
internal/scheduler/scheduler.go
internal/scheduler/shell.go
internal/tasks/tasks.go
samples/Download.sql
samples/Shell.sql
sql/tasks.sql

Task functions

---

Dockerfile

copy sql directory from building step

---

README.md

The job_add function example is missing the element "client_name". I add in all exemple.

The job_add function example is missing an element

---

.github/workflows/build.yml

Update to GoLang 1.13 in Actions

---

internal/pgengine/pgengine_test.go
samples/Shell.sql

Add test cases for samples scripts

---

internal/cmdparser/cmdparser.go
internal/pgengine/bootstrap.go
internal/scheduler/scheduler.go

Command line parameter --no-shell-tasks added

---

internal/pgengine/transaction.go
internal/scheduler/interval_chain.go
internal/scheduler/scheduler.go
internal/tasks/files.go
samples/Interval.sql

Interval execution implemented

@every and @after interval support added

---

.github/workflows/build.yml

GitHub Actions: `go test` + `postgresql`

---

internal/pgengine/access.go
internal/scheduler/scheduler.go

Fix FixSchedulerCrash() for parallel workers

---

internal/pgengine/access.go
internal/pgengine/bootstrap.go
internal/pgengine/log.go

Fix program terminating during connection loss and reconnection cycle

---

extras/grafana_status_overview.json

Add add Grafana dashboard to monitor chain execution stats

---

internal/scheduler/interval_chain.go

[-] fix "interval chains are not rescheduled if a database error occurs"

---

internal/pgengine/migration.go
internal/pgengine/sql_ddl.go
internal/pgengine/sql_job_functions.go

[+] add timetable.next_run(timetable.cron)

---

README.md

Explain the ignore_error flag on the scheduler working process.

---

README.md

A little fix in the documentation for the command line option.

Fix `--name` option in `--clientname`.

---

.github/workflows/build.yml
internal/scheduler/chain.go
internal/scheduler/chain_test.go
internal/scheduler/interval_chain.go
internal/scheduler/scheduler.go
internal/scheduler/scheduler_test.go
samples/Exclusive.sql
samples/Interval.sql

[+] Implement exclusive execution mode for chains, resolves #50

---

internal/pgengine/transaction.go

fix remote execution, fixes #164

---

.github/workflows/build.yml
.github/workflows/docker.yml
internal/migrator/migrator_test.go

Use pre-installed PostgreSQL in Github Actions

---

.github/workflows/build.yml
go.mod
go.sum
internal/pgengine/access.go
internal/pgengine/access_test.go
internal/pgengine/bootstrap.go
internal/pgengine/bootstrap_test.go
internal/pgengine/log.go
internal/pgengine/migration.go
internal/pgengine/migration_test.go
internal/pgengine/pgengine_test.go
internal/pgengine/sql_ddl.go
internal/scheduler/scheduler.go
internal/testutils/testutils.go

**WIP**:
* need to prettify tests
* reconsider `bootstrapping` flag usage

[!] reimplement session locking, resolves #149

---

internal/pgengine/transaction.go

[-] fix incorrect double quote escaping in task names, fixes #167

---

.github/workflows/release.yml

[+] push docker tags using the semver syntax by their git name
[-] fix deprecated set-env in GitHub Actions

[-] fix release action

---

.github/workflows/build.yml

[*] remove push trigger, enable pull_request and workflow_dispatch only 

---

internal/pgengine/access.go

[-] fix 'Scan error on column index 1, name "chain_id"...'

---

.github/workflows/build.yml
.github/workflows/docker.yml
go.mod
internal/pgengine/migration.go
internal/pgengine/sql/ddl.sql
internal/pgengine/sql/job_functions.sql
internal/pgengine/sql/json_schema.sql
internal/pgengine/sql/migrations/00070.sql
internal/pgengine/sql/migrations/00105.sql
internal/pgengine/sql/migrations/00108.sql
internal/pgengine/sql/migrations/00149.sql
internal/pgengine/sql/migrations/00178.sql
internal/pgengine/sql/migrations/00195.sql
internal/pgengine/sql/tasks.sql
internal/pgengine/sql_embed.go

[!] Use //go:embed for SQL scripts

---

internal/pgengine/bootstrap.go

[-] allow client name with dashes, fixes #214

---

internal/scheduler/scheduler.go

[-] fix deadlock when number of simultaneous chains exceeds DB pool size

---

internal/pgengine/access.go
internal/pgengine/bootstrap.go
internal/pgengine/copy.go
internal/pgengine/sql/tasks.sql
internal/tasks/database.go
internal/tasks/tasks.go
samples/Download.sql

[+] Add "CopyFromFile" BUILT-IN task

---

.github/workflows/build.yml
internal/pgengine/bootstrap.go
internal/pgengine/bootstrap_test.go
internal/pgengine/pgengine_test.go
internal/scheduler/chain_test.go
internal/scheduler/tasks.go
internal/scheduler/tasks_test.go

Increase v4 tests coverage

---

internal/pgengine/pgengine_test.go
internal/pgengine/transaction.go
internal/pgengine/transaction_test.go
internal/scheduler/chain.go
internal/scheduler/tasks.go
internal/scheduler/tasks_test.go
internal/tasks/files.go
internal/tasks/files_test.go

[+] add output for built-in and SQL tasks to the timetable.execution_log

---

go.mod
go.sum
internal/pgengine/access.go
internal/pgengine/pgengine_test.go
internal/pgengine/sql/ddl.sql
internal/pgengine/transaction.go
internal/pgengine/transaction_test.go
samples/RemoteDB.sql

[*] store remote database connection strings in chain table directly

---

internal/log/log.go
internal/pgengine/bootstrap.go
internal/pgengine/log_hook.go
internal/pgengine/log_hook_test.go
internal/pgengine/sql/ddl.sql

[+] add log hook for PostgreSQL using COPY machinery

---

.github/workflows/build.yml
internal/pgengine/bootstrap.go
internal/pgengine/bootstrap_test.go
internal/pgengine/sql/cron_functions.sql
internal/pgengine/sql/job_functions.sql
internal/pgengine/sql_embed.go

[-] fix 'date/time field value out of range' error in next_run(), fixes #237
[*] make go test fail fast in the build action

[!] rewrite cron handling from scratch

---

README.md
config.example.yaml
internal/config/cmdparser.go
internal/scheduler/chain.go
internal/scheduler/chain_test.go
internal/scheduler/scheduler.go

[+] add --cronworkers and --intervalworkers options under "Resource" group

---

internal/pgengine/access.go
internal/pgengine/access_test.go
internal/pgengine/migration.go
internal/pgengine/pgengine_test.go
internal/pgengine/sql/ddl.sql
internal/pgengine/sql/job_functions.sql
internal/pgengine/transaction.go
internal/scheduler/chain.go
internal/scheduler/interval_chain.go
main.go

[!] improve a running chains handling

---

config.example.yaml
go.mod
go.sum
internal/config/cmdparser.go
internal/log/log.go
internal/log/log_test.go
internal/migrator/migrator_test.go
internal/pgengine/bootstrap.go
internal/pgengine/pgengine_test.go
internal/scheduler/chain_test.go
internal/scheduler/interval_chain_test.go
internal/scheduler/scheduler_test.go
internal/scheduler/shell_test.go
internal/scheduler/tasks_test.go
main.go

[*] use dashes in long command-line parameters names

[+] add support for logging to file, closes #272

---

config.example.yaml
internal/config/cmdparser.go
internal/pgengine/sql/ddl.sql
internal/pgengine/transaction.go
internal/scheduler/chain.go
internal/scheduler/chain_test.go

[+] add --task-timeout command line parameter

[+] add task timeout, closes #271

---

internal/scheduler/chain.go
internal/scheduler/interval_chain.go
internal/scheduler/scheduler.go

[*] remove obsolete `intervalChainMutex`

[-] protect concurrent read and write of interval chains map, fixes #400

---

internal/pgengine/bootstrap.go
internal/pgengine/transaction.go

[-] fix executor context for pgengine.SetCurrentTaskContext(), fixes #541

---

internal/pgengine/sql/ddl.sql

[+] add comment for `timetable.task.autonomous` column

---

README.md

[-] fix example code in README.md
